### ISSUE TITLE
Better to change .m to .wl ?

### ISSUE THREAD

**Issue by kenkangxgwe** [antononcube/MathematicaForPrediction#1]
Hi @antononcube . Thank you for this awesome project, and I have spent serveral days reading your documents.
I do recommend to rename all the .m file to .wl, so it won't be messed up with objective-C and MATLAB file.

**Comment by antononcube** [comment]
Hi @kenkangxgwe , thank you for your note!

This is a good suggestion, I did not consider using .wl at this point. 

Unfortunately, all the packages have been proclaimed and referenced in blogs, forums, or other writings, so renaming them to have .wl extension is not a good option. I will consider using .wl for future packages.

**Comment by kenkangxgwe** [comment]
Thanks for your reply. Another problem was found when I read _Implementation-of-Object-Oriented-Programming-Design-Patterns-in-Mathematica_. There are hyphens in the reference links which redirect to the wrong addresses. Maybe Mathematica added those hyphens automatically, so would you mind delete them by hand?

**Comment by antononcube** [comment]
Good catch. I will fix the PDF. Meanwhile this (freshly committed) Markdown file might be more convenient to work with:

https://github.com/antononcube/MathematicaForPrediction/blob/master/MarkdownDocuments/Implementation-of-Object_Oriented-Programming-Design-Patterns-in-Mathematica.md

I verified the links in that file work correctly.
