### ISSUE TITLE
BestFitParameters

### ISSUE THREAD

**Issue by Thaddeus38** [antononcube/MathematicaForPrediction#2]
Hello, Anton
I am using your QuantileRegression.m package in Wolfram Language to make MonteCarlo simulations and compare the results of residual analysis from Ordinary Least Squares.

Thank you for writing this package and making it available.

To automate this simulation, I need the ability to extract the parameters from the _QuantileRegressionFit_, similar to ["BestFitParameters"] in _LinearModelFit_.
Is there a way to do this?
Please let me know. I would greatly appreciate your response.
Thank you in advance,
Thad

**Comment by antononcube** [comment]
Thank you for your kind words!
Please see the `MapThread` command in the example below.

```
data = Array[Prime, 300];
data = Transpose[{Range[Length[data]], data}];

funcs = {1, x, Log[x]};
qres = QuantileRegressionFit[data, funcs, x, {0.5, 0.7}];

MapThread[Join, {Map[Cases[#, _?NumberQ] &, qres] /. {} -> {0}, 
  Outer[Coefficient, qres, DeleteCases[funcs, _?NumberQ]]}]

(* {{3.16622*10^-10, 6.14692, 1.9274*10^-10}, {4.9249*10^-12, 
  6.34137, 8.47339*10^-13}} *)
```

**Comment by Thaddeus38** [comment]
Hello, Anton
Thank you for answering in such short notice and providing me with a concise, smartly written solution!
Cheers,
Thad

**Comment by antononcube** [comment]
Ok, good luck!
