### ISSUE TITLE
QuantileEnvelope example

### ISSUE THREAD

**Issue by surrutiaquir** [antononcube/MathematicaForPrediction#6]
Could you provide an example of how to use `QuantileEnvelope` or `QuantileEnvelopeRegion` similar to what you did [here](https://mathematica.stackexchange.com/a/106173/81788)?

**Comment by snailwowo** [comment]
(⊙o⊙)嗯 我已经收到你的来信啦

**Comment by antononcube** [comment]
Thank you for your interest to the Quantile Regression package!

There are several blog posts and presentations that discuss examples of using `QuantileEnvelope*` functions:

- ["Finding outliers in 2D and 3D numerical data"](https://mathematicaforprediction.wordpress.com/2016/04/30/finding-outliers-in-2d-and-3d-numerical-data/) (WordPress)
   - Here is the related [MSE answer](https://mathematica.stackexchange.com/a/114032/34008).
- [Answer](https://mathematica.stackexchange.com/a/134405/34008) to the MSE discussion ["How to make a random pebble?"](https://mathematica.stackexchange.com/questions/134392/how-to-make-a-random-pebble).

**Comment by snailwowo** [comment]
(⊙o⊙)嗯 我已经收到你的来信啦
